sudo: required
language: node_js
node_js:
  - '10'
branches:
  only:
    - develop
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
    - /^v[0-9]+\.[0-9]+\.[0-9]+-staging$/
jobs:
  include:
    - stage: lint
      if: branch =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      script:
        - set -e
        - npm link
        - npm run lint
        - set +e
    - stage: coverage
      if: branch =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      script:
        - set -e
        - npm run test:coverage
        - cat ./coverage/lcov.info | npx coveralls
        - set +e
        